spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory?useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 3306
server:
  port: 8888

mybatis:
  mapper-locations: com/dingrui/inventory/dao/mapping/**/*.xml
  type-aliases-package: com.**.domain